// Code generated by "stringer -type=SettingField"; DO NOT EDIT.

package source

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TemplateOrg-0]
	_ = x[TemplateRepo-1]
	_ = x[DinghyFilename-2]
	_ = x[AutoLockPipelines-3]
	_ = x[SpinnakerUIURL-4]
	_ = x[GitHubCredsPath-5]
	_ = x[GitHubToken-6]
	_ = x[GithubEndpoint-7]
	_ = x[GitLabToken-8]
	_ = x[GitLabEndpoint-9]
	_ = x[StashCredsPath-10]
	_ = x[StashUsername-11]
	_ = x[StashToken-12]
	_ = x[StashEndpoint-13]
	_ = x[FiatUser-14]
	_ = x[Logging-15]
	_ = x[Secrets-16]
	_ = x[ParserFormat-17]
	_ = x[RepoConfig-18]
	_ = x[Orca-19]
	_ = x[Front50-20]
	_ = x[Deck-21]
	_ = x[Echo-22]
	_ = x[Fiat-23]
	_ = x[Redis-24]
	_ = x[spinnakerSupplied-25]
	_ = x[Server-26]
	_ = x[Http-27]
	_ = x[WebhookValidations-28]
	_ = x[WebhookValidationEnabledProviders-29]
	_ = x[RepositoryRawdataProcessing-30]
	_ = x[LogEventTTLMinutes-31]
	_ = x[SQL-32]
}

const _SettingField_name = "TemplateOrgTemplateRepoDinghyFilenameAutoLockPipelinesSpinnakerUIURLGitHubCredsPathGitHubTokenGithubEndpointGitLabTokenGitLabEndpointStashCredsPathStashUsernameStashTokenStashEndpointFiatUserLoggingSecretsParserFormatRepoConfigOrcaFront50DeckEchoFiatRedisspinnakerSuppliedServerHttpWebhookValidationsWebhookValidationEnabledProvidersRepositoryRawdataProcessingLogEventTTLMinutesSQL"

var _SettingField_index = [...]uint16{0, 11, 23, 37, 54, 68, 83, 94, 108, 119, 133, 147, 160, 170, 183, 191, 198, 205, 217, 227, 231, 238, 242, 246, 250, 255, 272, 278, 282, 300, 333, 360, 378, 381}

func (i SettingField) String() string {
	if i < 0 || i >= SettingField(len(_SettingField_index)-1) {
		return "SettingField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SettingField_name[_SettingField_index[i]:_SettingField_index[i+1]]
}
