sequenceDiagram

  Engineer->>Github: Make PR for dinghyfile to App Repo
  Engineer->>Github: Merge PR to master
  Github ->>gate: Send a "merged to master" webhook
  gate ->> echo: Send event to event bus
  echo ->> dinghy: Forward event to dinghy
  dinghy ->> Github: Fetch's dinghyfile contents
  dinghy ->> redis: Fetches dependancy graph
  dinghy ->> dinghy: Creates Pipeline
  dinghy->> Front50: Save the pipeline

  Engineer->>Github: Make PR for moduleX to Modules Repo
  Engineer->>Github: Merge PR to master
  Github ->>gate: Send a "merged to master" webhook
  gate ->> echo: Send event to event bus
  echo ->> dinghy: Forward event to dinghy
  dinghy ->> Github: Fetch's moduleX's contents
  dinghy ->> redis: Fetches dependancy graph
  dinghy ->> dinghy: Creates pipeline1
  dinghy->> Front50: Save the pipeline1
  dinghy ->> dinghy: Creates pipeline2
  dinghy->> Front50: Save the pipeline2
  dinghy ->> dinghy: Creates pipeline3
  dinghy->> Front50: Save the pipeline3
