on:
  push:

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.14', "tip" ]
    name: Go ${{ matrix.go }} sample
    steps:
    - name: Get the version
      id:   get_version
      run:  echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Cache Build Dependencies  # Speeds up subsquent builds
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: go-${{ hashFiles('**/go.sum') }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v -mod=vendor ./...
